### ISSUE TITLE
It looks like there may be bugs in the operators

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty#1]
Taking a quick look over the new code, it seems like some of these operators will throw errors when executed.

For example, the postgres to csv operator references an undefined variable (should be self.postgres_conn_id):

https://github.com/chriscardillo/gusty/blob/master/gusty/operators/csv_to_postgres_operator.py#L61

Similar case in same file (csv_files never defined):

https://github.com/chriscardillo/gusty/blob/master/gusty/operators/csv_to_postgres_operator.py#L32

I wonder if it would be a good idea to set up some simple tests using pytest?

**Comment by machow** [comment]
PostgresHook appears undefined? (maybe I am misunderstanding how airflow imports these operators!)

https://github.com/chriscardillo/gusty/blob/master/gusty/operators/csv_to_postgres_operator.py#L61

**Comment by chriscardillo** [comment]
Resolved!
