### ISSUE TITLE
Documenting strategy for custom operators that use args and kwargs

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty#26]
From what I can tell, when gusty goes to instantiate an operator, it has two pieces in hand:

* the parameters specified in the task file (e.g. yaml header)
* the imported operator callable (e.g. a class)

It then does the following:

* get the named parameters off `operator.__init__`
* instantiate the operator, by passing only the parameters explicitly named in `operator.__init__`

AFAICT the reason for this is so additional information can be specified in yaml headers, even if it is not used to instantiate an operator. However, in practice, this also means that the common practice of wrapping/overloading a signature like `__init__(self, *args, **kwargs)` will not work.

This behavior makes sense to me, and is mentioned in the README. One area I wonder about though, is if the operator uses `*args`, or `**kwargs`. With gusty's current behavior, it might be worth mentioning that users will need to forward the `__signature__` attribute when wrapping / subclassing an operator (see this [SO post](https://stackoverflow.com/a/42422050/1144523)).

**Comment by machow** [comment]
Would also note that gusty's strategy of getting `operator.__init__` will fail for classes defined using things like `__new__`.

**Comment by machow** [comment]
Here's an example in airflow (at least in v1).

https://github.com/apache/airflow/blob/5786dcdc392f7a2649f398353a0beebef01c428e/airflow/contrib/operators/gcp_container_operator.py#L228-L235

**Comment by ccardillo-opal** [comment]
@machow - this `@wraps` implementation just came in handy for something I am working on. Thank you!!

**Comment by chriscardillo** [comment]
fixed by #29
