### ISSUE TITLE
external_dependencies fails for dags w/ schedule_interval "@once"

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty#32]
This seems like a tricky one, but it seems like for the externaltasksensor to succeed here, it would need to get the right execution_date_fn parameter. For monitoring a DAG that runs once, I think it'd be the dags start date (or one day earlier?).

**Comment by machow** [comment]
As a quick note--it seems challenging for a user to work around this, since execution_date_fn requires a callable, which can't really be specified easily in the yaml. This seems like an area where just being to return an operator or something in a .py file would be useful. The workaround is to create a one-off operator, which lets you specify execution_date as a string.

**Comment by chriscardillo** [comment]
You can specify an `execution_date_fn` in the `wait_for_defaults` dictionary in `create_dag`.

[Here](https://github.com/chriscardillo/gusty/blob/e997153e08770cdee74f0ed544b53960dec9c5bb/gusty/building.py#L217) are the `wait_for_defaults` available for setting.

Does this help to resolve the issue? I think this is more of an Airflow issue than a gusty issue.

**Comment by machow** [comment]
It seems like it depends on what gusty's external_dependencies feature is and what it isn't.

 Below is the description of the feature from the README:

> gusty also manages dependencies (within one DAG) and external dependencies (dependencies on tasks in other DAGs) for each task file you define. All you have to do is provide a list of dependencies or external_dependencies inside of a task file, and gusty will automatically set each task's dependencies and create external task sensors for any external dependencies listed.

It seems like as described this is a Gusty bug, as it has failed to create the correct external task sensor for an external dependency.

To be sure, I'm total on board with this being outside gusty's scope, since it's a very rare activity, and easily resolved by a user creating a custom operator!

(Also think the README is great as is, and don't want to give the impression I think it's misleading, only think about whose issue it is based off feature descriptions :)

**Comment by chriscardillo** [comment]
Going to close this for now. We'll see if it comes up again.
