### ISSUE TITLE
option in yaml header for adding documentation to task instance

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty#36]
Currently, gusty uses a custom field called `dependencies` to connect task instances together. Another area that might be helpful to handle for task instances is their documentation.

Note that currently task documentation seems to happen in a funky way:

![image](https://user-images.githubusercontent.com/2574498/142641182-5dcc407e-4ab5-4ca7-b21c-b783d8a450c5.png)

I can't figure out how to set this using yaml topmatter in gusty, so wonder if it somehow would need to be set another way? It seems like it'd be really handy if documentation could be set in topmatter and then appear on this screen!:

![image](https://user-images.githubusercontent.com/2574498/142641905-e8102a74-1122-4e57-ad11-5a583cec7f6f.png)

**Comment by chriscardillo** [comment]
Airflow 2.x offers [several documentation options for tasks via the BaseOperator](https://github.com/apache/airflow/blob/43e84ccb8c909ad78862a9411ab72dbac6c7169c/airflow/models/baseoperator.py#L667-L671). Using gusty with Airflow 2.x, if you added a `doc` or a `doc_md` block to your task definition file, you would get docs in Task Instance Details.

So I guess the short answer is - gusty already supports this because Airflow 2.x already supports this! :)

**Comment by machow** [comment]
Ah, thanks! Have you verified that this works? It is also documented in airflow v1 but does not work in the way you indicate. The documentation has not changed between versions, so I wonder if doc_md is not an argument to Operators????

**Comment by machow** [comment]
I'm seeing in airflow v2 docs that doc_md is an argument on the BaseOperator, but in airflow v1 it is only an argument to the DAG class, so it seems like this should work in v2?

**Comment by chriscardillo** [comment]
Verified it works in 2.x, but per your point I wouldn't expect it to work in 1.x. [v1.10 BaseOperator](https://github.com/apache/airflow/blob/v1-10-stable/airflow/models/baseoperator.py) doesn't have any of the docs fields.

For 1.x, as a test, maybe try adding a `doc` or `doc_md` to your operator and see if Airflow picks it up? 

On a separate note, while I am happy to help troubleshoot, I am unsure if this 1.x feature is something gusty should support..

**Comment by machow** [comment]
Yeah--that's fair, we're upgrading to v2, so should be able to just use `doc_md`, thanks for troubleshooting 😬😬😬!
