### ISSUE TITLE
For .py task, show python code as attribute on task instance

### ISSUE THREAD

**Issue by machow** [chriscardillo/gusty#39]
Currently, when a user creates a task using a `.py` file, Gusty automatically creates a handy task from it.

One added feature that would make it easy to browse these from the UI would be to add the python code that it ends up running as an attribute. For example, here is a task generated from a .sql file in https://github.com/cal-itp/data-infra, that shows the sql code in the task instance page. 

![image](https://user-images.githubusercontent.com/2574498/147507049-be70a1ae-8878-48db-8148-5fe7e1d4ec0f.png)

If the PythonCallable produced had an attribute like `python`, with the full python code used to create a python_callable, it seems like it would enable this kind of behavior!

**Comment by chriscardillo** [comment]
This is something Airflow would have to implement, not gusty.

**Comment by machow** [comment]
Could you say more? What is it about a sql file that allows gusty to produce a readable description (screenshot in original post), but not a .py file?

**Comment by machow** [comment]
Ah, I think I see! It looks like PythonOperator does not really report out anything about its callable (like its source, docstring etc..)
